import { PLACES, filterPlaces } from './places-data.js';
const $ = (selector) => document.querySelector(selector); const map = L.map('map', { scrollWheelZoom: false, attributionControl: false }).setView([41.59, -93.63], 12); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 18, attribution: '&copy; OpenStreetMap contributors' }).addTo(map); const markerLayer = L.layerGroup().addTo(map); let selectedId = null;
const state = { zip: '50309', neighborhood: 'all', service: 'all' }; [...new Set(PLACES.map((place) => place.neighborhood))].sort().forEach((name) => $('#neighborhood').insertAdjacentHTML('beforeend', `<option value="${name}">${name}</option>`));
function showToast(message) { const toast = $('#toast'); toast.textContent = message; toast.classList.add('show'); window.clearTimeout(showToast.timer); showToast.timer = window.setTimeout(() => toast.classList.remove('show'), 2800); }
function markerIcon(active = false) { return L.divIcon({ className: `pin${active ? ' pin-active' : ''}`, html: '<span aria-hidden="true"></span>', iconSize: [30, 30], iconAnchor: [15, 15] }); }
function selectPlace(id, focus = false) { selectedId = id; render(); if (focus) document.querySelector(`[data-place-id="${id}"]`)?.focus(); }
function render() { const matches = filterPlaces(PLACES, state); $('#near-label').textContent = state.zip || 'your area'; $('#result-count').textContent = `${matches.length} ${matches.length === 1 ? 'place' : 'places'}`; markerLayer.clearLayers(); matches.forEach((place) => L.marker([place.lat, place.lng], { icon: markerIcon(place.id === selectedId), title: place.name }).addTo(markerLayer).on('click', () => selectPlace(place.id, true))); if (matches.length) map.fitBounds(L.latLngBounds(matches.map((place) => [place.lat, place.lng])), { padding: [30, 30], maxZoom: 14 }); else map.setView([41.59, -93.63], 12); $('#place-list').innerHTML = matches.length ? matches.map((place) => `<article class="place-card${place.id === selectedId ? ' selected' : ''}" data-place-id="${place.id}" tabindex="0"><div class="place-photo" aria-hidden="true">${place.photo}</div><div class="place-body"><div class="place-title"><div><h3>${place.name}</h3><p>${place.neighborhood} · ${place.address}</p></div><span class="fresh">Verified ${place.verified}</span></div><p class="hours">${place.hours}</p><div class="service-tags">${place.services.map((service) => `<span>${service}</span>`).join('')}</div><button class="details" type="button" data-details="${place.id}">View details <span aria-hidden="true">→</span></button></div></article>`).join('') : '<div class="empty"><strong>No verified places found</strong><p>Try another ZIP code or clear a filter. We currently cover 50309, 50310, and 50010.</p><button class="secondary" type="button" id="empty-clear">Show all places</button></div>'; $('#status').textContent = matches.length ? `${matches.length} verified resource${matches.length === 1 ? '' : 's'} shown on the map and in the list.` : 'No results.'; document.querySelectorAll('.place-card').forEach((card) => { card.addEventListener('click', (event) => { if (!event.target.closest('button')) selectPlace(card.dataset.placeId); }); card.addEventListener('keydown', (event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); selectPlace(card.dataset.placeId); } }); }); document.querySelectorAll('[data-details]').forEach((button) => button.addEventListener('click', () => openDetails(button.dataset.details))); $('#empty-clear')?.addEventListener('click', clearFilters); renderInventory(matches); }
function renderInventory(matches) { const inventory = matches.flatMap((place) => place.inventory.map((item) => ({ ...item, place: place.name }))); $('#inventory-list').innerHTML = inventory.length ? inventory.map((item) => `<article class="inventory-card"><span class="inventory-icon" aria-hidden="true">✦</span><div><h3>${item.item}</h3><p>${item.place}</p><strong>${item.amount}</strong><small>${item.freshness}</small></div></article>`).join('') : '<p class="muted">Inventory appears when a verified place matches your filters.</p>'; }
function openDetails(id) { const place = PLACES.find((item) => item.id === id); $('#detail-content').innerHTML = `<p class="eyebrow">${place.kind.replace('-', ' ')}</p><h2 id="detail-title">${place.photo} ${place.name}</h2><p class="dialog-address">${place.address}</p><p><strong>${place.hours}</strong></p><h3>Services</h3><ul>${place.services.map((service) => `<li>${service}</li>`).join('')}</ul><p class="fresh">Last verified ${place.verified}. Inventory is provider-reported and can change.</p>`; $('#detail-dialog').showModal(); }
function clearFilters() { Object.assign(state, { zip: '', neighborhood: 'all', service: 'all' }); $('#zip').value = ''; $('#neighborhood').value = 'all'; $('#service').value = 'all'; selectedId = null; render(); }
$('#filter-form').addEventListener('submit', (event) => { event.preventDefault(); const zip = $('#zip').value.trim(); if (zip && !/^\d{5}$/.test(zip)) { showToast('Enter a valid 5-digit ZIP code.'); return; } state.zip = zip; selectedId = null; render(); showToast(zip ? `Showing verified places near ${zip}` : 'Showing all verified places'); }); $('#neighborhood').addEventListener('change', (event) => { state.neighborhood = event.target.value; selectedId = null; render(); }); $('#service').addEventListener('change', (event) => { state.service = event.target.value; selectedId = null; render(); }); $('#clear-filters').addEventListener('click', clearFilters); $('.dialog-close').addEventListener('click', () => $('#detail-dialog').close()); document.querySelectorAll('[data-action]').forEach((button) => button.addEventListener('click', () => showToast(button.dataset.action === 'help' ? 'A coordinator will be in touch.' : 'Thanks for helping keep HarvestLink current.'))); render();
